### ISSUE TITLE
programming guide

### ISSUE THREAD

**Issue by fjremnav** [sparkfun/BlackBoard#6]
There is no documentation in this repository. Do you know where I can find a programming guide?

Thanks,

**Comment by nseidle** [comment]
Sorry for the confusion. This board went red. You can read the RedBoard Plus Hookup Guide [here](https://learn.sparkfun.com/tutorials/redboard-plus-hookup-guide).

**Comment by fjremnav** [comment]
I don't understand your response. I just ordered a blackboard yesterday and
you tell me it went red.

Fc

**Comment by nseidle** [comment]
My apologies. The [BlackBoard](https://www.sparkfun.com/products/16282) has done well. So well, SparkFun decided to take the design and begin producing it regularly. The latest outcome of that is the [RedBoard Plus](https://www.sparkfun.com/products/18158). The BlackBoard and the RedBoard Plus are nearly identical. One of the main differences is that SparkX products almost never get documentation beyond the schematic, and an Arduino library (where applicable). In the case of the BlackBoard, there is no hookup guide or detailed information other than the schematic. Lucky for you, the BlackBoard 'went red', meaning the RedBoard Plus was created, and as such you can read the [RedBoard Plus hookup guide](https://learn.sparkfun.com/tutorials/redboard-plus-hookup-guide) for information about the specific pieces of hardware on the RedBoard, and infer those same features on its parent (and influence) the BlackBoard.  

We continue to sell the BlackBoard as it is our sandbox. We modify the design as users recommend and request changes, and we can do so easily because it does *not* have documentation. Its design is always in flux.

I hope that makes a bit more sense.

**Comment by fjremnav** [comment]
Nathan

   I received blackboard C today and connect to my PC. Use sketch SW to
program it. Sketch asks me which arduino board is.
Is this blackboard C  Arduino nano or uno or something else?

FC
